---
title: "LifeGenMon Abies SNP - export to genalex"
author: "Nikos Tourvas"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
# bibliography: library.bib
output:
  html_notebook:
    code_folding: hide
    theme: united
    toc: yes
    toc_float: yes
    toc_depth: 3
  html_document:
    code_folding: hide
    theme: united
    toc: yes
    ## toc_float: yes
  pdf_document:
    toc: yes
always_allow_html: yes
---

```{r}
library(popprxl)
library(adegenet)
library(pegas)
library(tidyverse)
```


# Import csv
```{r import_csv}
snp <- read.csv("../data/Genotyping-1841.025-03 Grid_EDITED.csv", 
                header = T,
                na.strings = c("?", "Uncallable", "Bad", "Missing")
               # ,stringsAsFactors = T
               , check.names = F # default is TRUE, and changes the dashes to dots - which created problems
               )
# snp
```

<!-- ## Transform sample names -->
<!-- #### This will allow hierarchical analysis when applicable -->
<!-- #### Country / Species / Pop / Plot -->
```{r include=F}
library(tidyverse)

snp <- snp %>% 
  mutate(Genotype = str_replace_all(Genotype, "^AB", "GR_AB_A_")) %>% #GR_Adult
  mutate(Genotype = str_replace_all(Genotype, "^RAB", "GR_AB")) %>% #GR_Regen
  
  mutate(Genotype = str_replace_all(Genotype, "_A_", "_A_1_")) %>% 
  
  mutate(Genotype = str_replace_all(Genotype, "NR", "NR_"))
```

<!-- ## Remove samples that consistently do not amplify -->
```{r include=F}
# 
# snp_fil <- snp %>% 
#         filter(snpa != "Bad")
# 
# snp_fil
```

<!-- ### Create a df following the guidelines of the loci format -->
```{r include=F}
snp_loci_format <- as.data.frame(sapply(snp, gsub, pattern=':', replacement='/') )
# snp_loci_format <- as.data.frame(sapply(snp_loci_format, gsub, pattern=".", replacement="_"))
snp_loci_format <- snp_loci_format[,-1]
rownames(snp_loci_format) <- snp[,1]

# snp_loci_format
```

```{r include=F}
## Add a second column for population

pop1 <- replicate(124, "DE_AAL_A_1")
pop2 <- replicate(16, "DE_AAL_NR_1")
pop3 <- replicate(16, "DE_AAL_NR_2")
pop4 <- replicate(16, "DE_AAL_NR_3")
pop5 <- replicate(16, "DE_AAL_NR_4")
pop6 <- replicate(124, "GR_AB_A_1")
pop7 <- replicate(20, "GR_AB_NR_1")
pop8 <- replicate(18, "GR_AB_NR_2")
pop9 <- replicate(16, "GR_AB_NR_3")
pop10 <- replicate(10, "GR_AB_NR_4")
pop11 <- replicate(124, "SI_AAL_A_1")
pop12 <- replicate(16, "SI_AAL_NR_1")
pop13 <- replicate(16, "SI_AAL_NR_2")
pop14 <- replicate(16, "SI_AAL_NR_3")
pop15 <- replicate(16, "SI_AAL_NR_4")

pop <- c(pop1, pop2, pop3, pop4, pop5, pop6,
         pop7, pop8, pop9, pop10, pop11,
         pop12, pop13, pop14, pop15)

# pop

snp_loci_format <- add_column(snp_loci_format, pop, .before = "contig00241-160")

# snp_loci_format
```

<!-- ## Create genind object -->
```{r include=F}
library(pegas)

data <- as.loci(snp_loci_format, 
                col.pop = 1
                ,allele.sep = "/")
# data

obj_origin <- loci2genind(data,)
# obj_origin
```

<!-- ### stratify data set -->
```{r include=F}
strata_df <- as.data.frame(snp_loci_format$pop)
colnames(strata_df) <- "strata"
strata_df <- separate(strata_df, col = strata, sep="_", 
                      into = c("Country", 
                               "Species", 
                               "Pop", 
                               "Plot"))
strata(obj_origin) <- strata_df

setPop(obj_origin) <- ~Country
# obj_origin
```

<!-- #
Data filtering -->

<!-- ### Remove uninformative (monomorphic) loci -->
```{r include=F}
library(poppr)
obj <- informloci(obj_origin, MAF = 0)
```

<!-- ### Filter out missing data -->
```{r cache=F, fig.width=10, dpi=300, include=FALSE}
threshold <- 0.10

obj <- missingno(obj, type = "loci", cutoff = threshold)

obj <- missingno(obj, type = "genotypes", cutoff = threshold)
```

<!-- ### Remove uninformative loci -->
```{r include=F}
library(poppr)

maf <- 0.05 
obj <- informloci(obj, MAF = maf)
```

### Data filtering thresholds
```{r}
paste("SNP loci:", threshold*100, 
      "% missing data across populations", sep=" ")
```

```{r}
paste("Individuals:", threshold*100, "% missing data", sep=" ")
```

```{r}
paste("SNP loci with minor allele frequency <", maf)
```

### Data set details after data filtering:
```{r}
paste(nInd(obj), "individuals", "and", nLoc(obj), "loci", sep=" ")
```

## Export to df for use in GenAlEx
```{r}
# convert back to loci format
obj_loci <- genind2loci(obj)

# Split alleles 
library(splitstackshape)

vec <- colnames(obj_loci[-1])

df <- cSplit(indt = obj_loci, splitCols = vec,
                sep = "/", 
# needed so that it does not convert "T" to logical ("TRUE")
               type.convert = F) 

# add genotype col
df <- add_column(df, rownames(obj_loci), .before = "population")

colnames(df) <- c("Genotype", "Population", 
                  rep(colnames(obj_loci[-1]), each = 2) )

# replace NAs with 0
df[is.na(df)] <- 0

# recode nucleotide bases to numbers
df[df=="A"] <- 1
df[df=="T"] <- 2
df[df=="G"] <- 3
df[df=="C"] <- 4

head(df)

write.csv(df, file="../data/LGM_SNP_Abies.csv", row.names = F)
```
